"""Build a larger vocabulary of concrete nouns for the Convergence game.

Starts from the hand-picked words in data/vocab_1000.txt, then adds the most common single-word nouns
rated concrete (at least 4 out of 5) in the Brysbaert et al. (2014) concreteness ratings:
https://github.com/ArtsEngine/concreteness

Plurals are removed with WordNet, profanity with better-profanity, and words that would be awkward
on a projector are listed in data/vocab_exclude.txt. Review the output before using it in a talk.

    uv run --with better-profanity --with nltk build_vocab.py --size 5000
"""

import argparse
import csv
import urllib.request
from pathlib import Path

import nltk
from better_profanity import profanity
from nltk.corpus import wordnet

RATINGS_URL = "https://raw.githubusercontent.com/ArtsEngine/concreteness/master/Concreteness_ratings_Brysbaert_et_al_BRM.txt"

# WordNet treats these as plurals of another noun, but they're better known as their own things
PLURAL_ONLY = {"pants", "glasses", "jeans", "shorts", "scissors", "news"}


def load_ratings() -> list[dict]:
    with urllib.request.urlopen(RATINGS_URL) as response:
        lines = response.read().decode("utf-8").splitlines()
    return list(csv.DictReader(lines, delimiter="\t"))


def concrete_nouns(ratings: list[dict], min_concreteness: float) -> list[str]:
    """Single-word nouns at or above the concreteness threshold, most frequent first."""
    nouns = [
        row
        for row in ratings
        if row["Bigram"] == "0" and row["Dom_Pos"] == "Noun" and row["Word"].isalpha() and row["Word"].islower() and len(row["Word"]) >= 3 and float(row["Conc.M"]) >= min_concreteness
    ]
    nouns.sort(key=lambda row: -int(row["SUBTLEX"]))
    return [row["Word"] for row in nouns]


def is_plural(word: str) -> bool:
    if word.endswith("ss") or word in PLURAL_ONLY:
        return False
    return any(base != word for base in wordnet._morphy(word, wordnet.NOUN))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--size", type=int, default=5000, help="Number of words (default: 5000).")
    parser.add_argument("--min-concreteness", type=float, default=4.0, help="Minimum mean concreteness rating, 1-5 (default: 4.0).")
    parser.add_argument("--seed-vocab", type=Path, default=Path("data/vocab_1000.txt"), help="Hand-picked words to always include.")
    parser.add_argument("--exclude", type=Path, default=Path("data/vocab_exclude.txt"), help="Words to leave out.")
    parser.add_argument("--output", type=Path, default=Path("data/vocab_5000.txt"), help="Output file.")
    args = parser.parse_args()

    seed = [line.strip() for line in args.seed_vocab.read_text().splitlines() if line.strip() and not line.startswith("#")]
    excluded = {word for line in args.exclude.read_text().splitlines() if not line.startswith("#") for word in line.split()}
    words = list(dict.fromkeys(seed))
    chosen = set(words)
    profanity.load_censor_words()
    nltk.download("wordnet", quiet=True)
    for word in concrete_nouns(load_ratings(), args.min_concreteness):
        if len(words) >= args.size:
            break
        if word in chosen or word in excluded or profanity.contains_profanity(word) or is_plural(word):
            continue
        words.append(word)
        chosen.add(word)

    header = [
        f"# Vocabulary of {len(words)} concrete nouns for the Convergence game, generated by build_vocab.py.",
        "# Hand-picked words from vocab_1000.txt first, then common nouns from the Brysbaert et al. (2014) concreteness ratings.",
    ]
    args.output.write_text("\n".join(header + words) + "\n")
    print(f"Wrote {len(words)} words to {args.output}")


if __name__ == "__main__":
    main()
